# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Argonaut Digital Collection

description: > 
  A digital collection of UIdaho student newspaper, the Argonaut, 1989 to 2010.
# baseurl: "/digital/argonaut" # the subpath of your site, e.g. /blog
baseurl: "/argonautweb"
# url: "http://www.lib.uidaho.edu" # the base hostname & protocol for your site
url: "https://evanwill.github.io"

# Build settings
markdown: kramdown

# deploy commands https://gist.github.com/evanwill/12af569da8b53f037d4f507a0254f76c
# deploy:
# - rsync -r ./ ../../test/

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'argoyears'
    template: 'year'
    name: 'date'
    dir: 'year2'
    extension: 'html'
